import Phaser from 'phaser';

export class BootScene extends Phaser.Scene {
  constructor() { super('BootScene'); }

  preload() {
    // Load ship assets generated by AI
    this.load.image('ship_p1', 'assets/ship_p1.jpg');
    this.load.image('ship_p2', 'assets/ship_p2.jpg');
  }

  create() {
    this.createStarfield();
    this.createBulletTexture();
    this.createExplosionFrames();
    this.scene.start('MenuScene');
  }

  private createStarfield() {
    const rt = this.add.renderTexture(0, 0, 1280, 720);
    const g = this.add.graphics();
    for (let i = 0; i < 200; i++) {
      const x = Phaser.Math.Between(0, 1280);
      const y = Phaser.Math.Between(0, 720);
      const r = Math.random() < 0.05 ? 2 : 1;
      const alpha = Phaser.Math.FloatBetween(0.3, 1.0);
      g.fillStyle(0xffffff, alpha);
      g.fillCircle(x, y, r);
    }
    rt.draw(g);
    rt.saveTexture('starfield');
    g.destroy();
    rt.destroy();
  }

  private createBulletTexture() {
    const g = this.add.graphics();
    // Glowing bullet
    g.fillStyle(0xffffff, 0.3);
    g.fillCircle(8, 4, 7);
    g.fillStyle(0xffffff, 0.8);
    g.fillCircle(8, 4, 4);
    g.fillStyle(0xffffff, 1);
    g.fillRect(2, 2, 12, 4);
    g.generateTexture('bullet_base', 16, 8);
    g.destroy();
  }

  private createExplosionFrames() {
    for (let i = 0; i < 6; i++) {
      const r = (i + 1) * 9;
      const g = this.add.graphics();
      const alpha = 1 - i * 0.15;
      g.fillStyle(0xff8800, alpha);
      g.fillCircle(r + 2, r + 2, r);
      g.fillStyle(0xffdd00, alpha * 0.8);
      g.fillCircle(r + 2, r + 2, r * 0.6);
      g.fillStyle(0xffffff, alpha * 0.5);
      g.fillCircle(r + 2, r + 2, r * 0.3);
      g.generateTexture(`explosion_${i}`, (r + 2) * 2, (r + 2) * 2);
      g.destroy();
    }
  }
}
